//ExtraTiC Patches - Universal

#Alloying
mods.tconstruct.Smeltery.addAlloy(<liquid:blutonium.molten> * 144, [<liquid:cyanite> * 288, <liquid:redstone> * 144, <liquid:lead.molten> * 72]);
mods.tconstruct.Smeltery.addAlloy(<liquid:ludicrite.molten> * 576, [<liquid:blutonium.molten> * 576, <liquid:ender> * 500, <liquid:emerald.liquid> * 640, <liquid:enderium.molten> * 432]);

#Melting
mods.tconstruct.Smeltery.addMelting(<Botania:manaResource:0>, <liquid:manasteel.molten> * 144, 430, <Botania:storage:0>);
mods.tconstruct.Smeltery.addMelting(<Botania:storage:0>, <liquid:manasteel.molten> * 1296, 430, <Botania:storage:0>);
mods.tconstruct.Smeltery.addMelting(<Botania:manaResource:7>, <liquid:elementium.molten> * 144, 530, <Botania:storage:2>);
mods.tconstruct.Smeltery.addMelting(<Botania:storage:2>, <liquid:elementium.molten> * 1296, 530, <Botania:storage:2>);
mods.tconstruct.Smeltery.addMelting(<Botania:manaResource:4>, <liquid:terrasteel.molten> * 144, 430, <Botania:storage:1>);
mods.tconstruct.Smeltery.addMelting(<Botania:storage:1>, <liquid:terrasteel.molten> * 1296, 430, <Botania:storage:1>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:toolrod:145>, <liquid:manasteel.molten> * 72, 430, <Botania:storage:0>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:toolrod:147>, <liquid:elementium.molten> * 72, 530, <Botania:storage:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:toolrod:146>, <liquid:terrasteel.molten> * 72, 550, <Botania:storage:1>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:pickaxeHead:145>, <liquid:manasteel.molten> * 144, 430, <Botania:storage:0>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:shovelHead:145>, <liquid:manasteel.molten> * 144, 430, <Botania:storage:0>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:axeHead:145>, <liquid:manasteel.molten> * 144, 430, <Botania:storage:0>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:swordBlade:145>, <liquid:manasteel.molten> * 144, 430, <Botania:storage:0>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:largeGuard:145>, <liquid:manasteel.molten> * 72, 430, <Botania:storage:0>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:mediumGuard:145>, <liquid:manasteel.molten> * 72, 430, <Botania:storage:0>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:crossbar:145>, <liquid:manasteel.molten> * 72, 430, <Botania:storage:0>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:binding:145>, <liquid:manasteel.molten> * 72, 430, <Botania:storage:0>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:frypanHead:145>, <liquid:manasteel.molten> * 144, 430, <Botania:storage:0>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:battelSign:145>, <liquid:manasteel.molten> * 144, 430, <Botania:storage:0>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:knifeBlade:145>, <liquid:manasteel.molten> * 72, 430, <Botania:storage:0>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:chiselHead:145>, <liquid:manasteel.molten> * 72, 430, <Botania:storage:0>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:toughrod:145>, <liquid:manasteel.molten> * 432, 430, <Botania:storage:0>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:toughbind:145>, <liquid:manasteel.molten> * 432, 430, <Botania:storage:0>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:largeplate:145>, <liquid:manasteel.molten> * 1152, 430, <Botania:storage:0>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:lumberaxeHead:145>, <liquid:manasteel.molten> * 1152, 430, <Botania:storage:0>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:scytheHead:145>, <liquid:manasteel.molten> * 1152, 430, <Botania:storage:0>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:excavatorHead:145>, <liquid:manasteel.molten> * 1152, 430, <Botania:storage:0>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:largeSwordBlade:145>, <liquid:manasteel.molten> * 1152, 430, <Botania:storage:0>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:hammerHead:145>, <liquid:manasteel.molten> * 1152, 430, <Botania:storage:0>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:fullGuard:145>, <liquid:manasteel.molten> * 432, 430, <Botania:storage:0>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:arrowhead:145>, <liquid:manasteel.molten> * 144, 430, <Botania:storage:0>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:shuriken:145>, <liquid:manasteel.molten> * 72, 430, <Botania:storage:0>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:CrossbowLimb:145>, <liquid:manasteel.molten> * 576, 430, <Botania:storage:0>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:CrossbowBody:145>, <liquid:manasteel.molten> * 720, 430, <Botania:storage:0>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:BowLimb:145>,<liquid:manasteel.molten> * 216, 430, <Botania:storage:0>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:pickaxeHead:147>, <liquid:elementium.molten> * 144, 530, <Botania:storage:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:shovelHead:147>, <liquid:elementium.molten> * 144, 530, <Botania:storage:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:axeHead:147>, <liquid:elementium.molten> * 144, 530, <Botania:storage:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:swordBlade:147>, <liquid:elementium.molten> * 144, 530, <Botania:storage:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:largeGuard:147>, <liquid:elementium.molten> * 72, 530, <Botania:storage:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:mediumGuard:147>, <liquid:elementium.molten> * 72, 530, <Botania:storage:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:crossbar:147>, <liquid:elementium.molten> * 72, 530, <Botania:storage:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:binding:147>, <liquid:elementium.molten> * 72, 530, <Botania:storage:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:frypanHead:147>, <liquid:elementium.molten> * 144, 530, <Botania:storage:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:battelSign:147>, <liquid:elementium.molten> * 144, 530, <Botania:storage:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:knifeBlade:147>, <liquid:elementium.molten> * 72, 530, <Botania:storage:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:chiselHead:147>, <liquid:elementium.molten> * 72, 530, <Botania:storage:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:toughrod:147>, <liquid:elementium.molten> * 432, 530, <Botania:storage:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:toughbind:147>, <liquid:elementium.molten> * 432, 530, <Botania:storage:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:largeplate:147>, <liquid:elementium.molten> * 1152, 530, <Botania:storage:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:lumberaxeHead:147>, <liquid:elementium.molten> * 1152, 530, <Botania:storage:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:scytheHead:147>, <liquid:elementium.molten> * 1152, 530, <Botania:storage:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:excavatorHead:147>, <liquid:elementium.molten> * 1152, 530, <Botania:storage:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:largeSwordBlade:147>, <liquid:elementium.molten> * 1152, 530, <Botania:storage:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:hammerHead:147>, <liquid:elementium.molten> * 1152, 530, <Botania:storage:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:fullGuard:147>, <liquid:elementium.molten> * 432, 530, <Botania:storage:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:arrowhead:147>, <liquid:elementium.molten> * 144, 530, <Botania:storage:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:shuriken:147>, <liquid:elementium.molten> * 72, 530, <Botania:storage:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:CrossbowLimb:147>, <liquid:elementium.molten> * 576, 530, <Botania:storage:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:CrossbowBody:147>, <liquid:elementium.molten> * 720, 530, <Botania:storage:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:BowLimb:147>,<liquid:elementium.molten> * 216, 530, <Botania:storage:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:pickaxeHead:146>, <liquid:terrasteel.molten> * 144, 550, <Botania:storage:1>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:shovelHead:146>, <liquid:terrasteel.molten> * 144, 550, <Botania:storage:1>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:axeHead:146>, <liquid:terrasteel.molten> * 144, 550, <Botania:storage:1>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:swordBlade:146>, <liquid:terrasteel.molten> * 144, 550, <Botania:storage:1>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:largeGuard:146>, <liquid:terrasteel.molten> * 72, 550, <Botania:storage:1>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:mediumGuard:146>, <liquid:terrasteel.molten> * 72, 550, <Botania:storage:1>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:crossbar:146>, <liquid:terrasteel.molten> * 72, 550, <Botania:storage:1>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:binding:146>, <liquid:terrasteel.molten> * 72, 550, <Botania:storage:1>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:frypanHead:146>, <liquid:terrasteel.molten> * 144, 550, <Botania:storage:1>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:battelSign:146>, <liquid:terrasteel.molten> * 144, 550, <Botania:storage:1>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:knifeBlade:146>, <liquid:terrasteel.molten> * 72, 550, <Botania:storage:1>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:chiselHead:146>, <liquid:terrasteel.molten> * 72, 550, <Botania:storage:1>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:toughrod:146>, <liquid:terrasteel.molten> * 432, 550, <Botania:storage:1>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:toughbind:146>, <liquid:terrasteel.molten> * 432, 550, <Botania:storage:1>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:largeplate:146>, <liquid:terrasteel.molten> * 1152, 550, <Botania:storage:1>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:lumberaxeHead:146>, <liquid:terrasteel.molten> * 1152, 550, <Botania:storage:1>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:scytheHead:146>, <liquid:terrasteel.molten> * 1152, 550, <Botania:storage:1>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:excavatorHead:146>, <liquid:terrasteel.molten> * 1152, 550, <Botania:storage:1>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:largeSwordBlade:146>, <liquid:terrasteel.molten> * 1152, 550, <Botania:storage:1>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:hammerHead:146>, <liquid:terrasteel.molten> * 1152, 550, <Botania:storage:1>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:fullGuard:146>, <liquid:terrasteel.molten> * 432, 550, <Botania:storage:1>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:arrowhead:146>, <liquid:terrasteel.molten> * 144, 550, <Botania:storage:1>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:shuriken:146>, <liquid:terrasteel.molten> * 72, 550, <Botania:storage:1>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:CrossbowLimb:146>, <liquid:terrasteel.molten> * 576, 550, <Botania:storage:1>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:CrossbowBody:146>, <liquid:terrasteel.molten> * 720, 550, <Botania:storage:1>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:BowLimb:146>,<liquid:terrasteel.molten> * 216, 550, <Botania:storage:1>);

#Casting
mods.tconstruct.Casting.addBasinRecipe(<Botania:storage:0>, <liquid:manasteel.molten> * 1296, null, false, 300);
mods.tconstruct.Casting.addTableRecipe(<Botania:manaResource:0>, <liquid:manasteel.molten> * 144, <TConstruct:metalPattern:0>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:toolrod:145>, <liquid:manasteel.molten> * 72, <TConstruct:metalPattern:1>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:pickaxeHead:145>, <liquid:manasteel.molten> * 144, <TConstruct:metalPattern:2>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:shovelHead:145>, <liquid:manasteel.molten> * 144, <TConstruct:metalPattern:3>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:axeHead:145>, <liquid:manasteel.molten> * 144, <TConstruct:metalPattern:4>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:swordBlade:145>, <liquid:manasteel.molten> * 144, <TConstruct:metalPattern:5>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:largeGuard:145>, <liquid:manasteel.molten> * 72, <TConstruct:metalPattern:6>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:mediumGuard:145>, <liquid:manasteel.molten> * 72, <TConstruct:metalPattern:7>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:crossbar:145>, <liquid:manasteel.molten> * 72, <TConstruct:metalPattern:8>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:binding:145>, <liquid:manasteel.molten> * 72, <TConstruct:metalPattern:9>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:frypanHead:145>, <liquid:manasteel.molten> * 144, <TConstruct:metalPattern:10>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:battelSign:145>, <liquid:manasteel.molten> * 144, <TConstruct:metalPattern:11>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:knifeBlade:145>, <liquid:manasteel.molten> * 72, <TConstruct:metalPattern:12>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:chiselHead:145>, <liquid:manasteel.molten> * 72, <TConstruct:metalPattern:13>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:toughrod:145>, <liquid:manasteel.molten> * 432, <TConstruct:metalPattern:14>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:toughbind:145>, <liquid:manasteel.molten> * 432, <TConstruct:metalPattern:15>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:largeplate:145>, <liquid:manasteel.molten> * 1152, <TConstruct:metalPattern:16>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:lumberaxeHead:145>, <liquid:manasteel.molten> * 1152, <TConstruct:metalPattern:17>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:scytheHead:145>, <liquid:manasteel.molten> * 1152, <TConstruct:metalPattern:18>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:excavatorHead:145>, <liquid:manasteel.molten> * 1152, <TConstruct:metalPattern:19>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:largeSwordBlade:145>, <liquid:manasteel.molten> * 1152, <TConstruct:metalPattern:20>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:hammerHead:145>, <liquid:manasteel.molten> * 1152, <TConstruct:metalPattern:21>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:fullGuard:145>, <liquid:manasteel.molten> * 432, <TConstruct:metalPattern:22>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:arrowhead:145>, <liquid:manasteel.molten> * 144, <TConstruct:metalPattern:25>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:shuriken:145>, <liquid:manasteel.molten> * 72, <TConstruct:Cast:0>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:CrossbowLimb:145>, <liquid:manasteel.molten> * 576, <TConstruct:Cast:1>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:CrossbowBody:145>, <liquid:manasteel.molten> * 720, <TConstruct:Cast:2>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:BowLimb:145>, <liquid:manasteel.molten> * 216, <TConstruct:Cast:3>, false, 100);
mods.tconstruct.Casting.addBasinRecipe(<Botania:storage:2>, <liquid:elementium.molten> * 1296, null, false, 300);
mods.tconstruct.Casting.addTableRecipe(<Botania:manaResource:7>, <liquid:elementium.molten> * 144, <TConstruct:metalPattern:0>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:toolrod:147>, <liquid:elementium.molten> * 72, <TConstruct:metalPattern:1>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:pickaxeHead:147>, <liquid:elementium.molten> * 144, <TConstruct:metalPattern:2>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:shovelHead:147>, <liquid:elementium.molten> * 144, <TConstruct:metalPattern:3>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:axeHead:147>, <liquid:elementium.molten> * 144, <TConstruct:metalPattern:4>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:swordBlade:147>, <liquid:elementium.molten> * 144, <TConstruct:metalPattern:5>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:largeGuard:147>, <liquid:elementium.molten> * 72, <TConstruct:metalPattern:6>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:mediumGuard:147>, <liquid:elementium.molten> * 72, <TConstruct:metalPattern:7>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:crossbar:147>, <liquid:elementium.molten> * 72, <TConstruct:metalPattern:8>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:binding:147>, <liquid:elementium.molten> * 72, <TConstruct:metalPattern:9>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:frypanHead:147>, <liquid:elementium.molten> * 144, <TConstruct:metalPattern:10>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:battelSign:147>, <liquid:elementium.molten> * 144, <TConstruct:metalPattern:11>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:knifeBlade:147>, <liquid:elementium.molten> * 72, <TConstruct:metalPattern:12>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:chiselHead:147>, <liquid:elementium.molten> * 72, <TConstruct:metalPattern:13>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:toughrod:147>, <liquid:elementium.molten> * 432, <TConstruct:metalPattern:14>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:toughbind:147>, <liquid:elementium.molten> * 432, <TConstruct:metalPattern:15>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:largeplate:147>, <liquid:elementium.molten> * 1152, <TConstruct:metalPattern:16>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:lumberaxeHead:147>, <liquid:elementium.molten> * 1152, <TConstruct:metalPattern:17>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:scytheHead:147>, <liquid:elementium.molten> * 1152, <TConstruct:metalPattern:18>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:excavatorHead:147>, <liquid:elementium.molten> * 1152, <TConstruct:metalPattern:19>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:largeSwordBlade:147>, <liquid:elementium.molten> * 1152, <TConstruct:metalPattern:20>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:hammerHead:147>, <liquid:elementium.molten> * 1152, <TConstruct:metalPattern:21>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:fullGuard:147>, <liquid:elementium.molten> * 432, <TConstruct:metalPattern:22>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:arrowhead:147>, <liquid:elementium.molten> * 144, <TConstruct:metalPattern:25>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:shuriken:147>, <liquid:elementium.molten> * 72, <TConstruct:Cast:0>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:CrossbowLimb:147>, <liquid:elementium.molten> * 576, <TConstruct:Cast:1>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:CrossbowBody:147>, <liquid:elementium.molten> * 720, <TConstruct:Cast:2>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:BowLimb:147>, <liquid:elementium.molten> * 216, <TConstruct:Cast:3>, false, 100);
mods.tconstruct.Casting.addBasinRecipe(<Botania:storage:1>, <liquid:terrasteel.molten> * 1296, null, false, 300);
mods.tconstruct.Casting.addTableRecipe(<Botania:manaResource:4>, <liquid:terrasteel.molten> * 144, <TConstruct:metalPattern:0>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:toolrod:146>, <liquid:terrasteel.molten> * 72, <TConstruct:metalPattern:1>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:pickaxeHead:146>, <liquid:terrasteel.molten> * 144, <TConstruct:metalPattern:2>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:shovelHead:146>, <liquid:terrasteel.molten> * 144, <TConstruct:metalPattern:3>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:axeHead:146>, <liquid:terrasteel.molten> * 144, <TConstruct:metalPattern:4>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:swordBlade:146>, <liquid:terrasteel.molten> * 144, <TConstruct:metalPattern:5>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:largeGuard:146>, <liquid:terrasteel.molten> * 72, <TConstruct:metalPattern:6>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:mediumGuard:146>, <liquid:terrasteel.molten> * 72, <TConstruct:metalPattern:7>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:crossbar:146>, <liquid:terrasteel.molten> * 72, <TConstruct:metalPattern:8>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:binding:146>, <liquid:terrasteel.molten> * 72, <TConstruct:metalPattern:9>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:frypanHead:146>, <liquid:terrasteel.molten> * 144, <TConstruct:metalPattern:10>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:battelSign:146>, <liquid:terrasteel.molten> * 144, <TConstruct:metalPattern:11>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:knifeBlade:146>, <liquid:terrasteel.molten> * 72, <TConstruct:metalPattern:12>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:chiselHead:146>, <liquid:terrasteel.molten> * 72, <TConstruct:metalPattern:13>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:toughrod:146>, <liquid:terrasteel.molten> * 432, <TConstruct:metalPattern:14>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:toughbind:146>, <liquid:terrasteel.molten> * 432, <TConstruct:metalPattern:15>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:largeplate:146>, <liquid:terrasteel.molten> * 1152, <TConstruct:metalPattern:16>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:lumberaxeHead:146>, <liquid:terrasteel.molten> * 1152, <TConstruct:metalPattern:17>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:scytheHead:146>, <liquid:terrasteel.molten> * 1152, <TConstruct:metalPattern:18>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:excavatorHead:146>, <liquid:terrasteel.molten> * 1152, <TConstruct:metalPattern:19>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:largeSwordBlade:146>, <liquid:terrasteel.molten> * 1152, <TConstruct:metalPattern:20>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:hammerHead:146>, <liquid:terrasteel.molten> * 1152, <TConstruct:metalPattern:21>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:fullGuard:146>, <liquid:terrasteel.molten> * 432, <TConstruct:metalPattern:22>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:arrowhead:146>, <liquid:terrasteel.molten> * 144, <TConstruct:metalPattern:25>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:shuriken:146>, <liquid:terrasteel.molten> * 72, <TConstruct:Cast:0>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:CrossbowLimb:146>, <liquid:terrasteel.molten> * 576, <TConstruct:Cast:1>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:CrossbowBody:146>, <liquid:terrasteel.molten> * 720, <TConstruct:Cast:2>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:BowLimb:146>, <liquid:terrasteel.molten> * 216, <TConstruct:Cast:3>, false, 100);

#Melting
mods.tconstruct.Smeltery.addMelting(<EnderIO:itemAlloy:6>, <liquid:dark.steel.molten> * 144, 770, <EnderIO:blockIngotStorage:6>);
mods.tconstruct.Smeltery.addMelting(<EnderIO:blockIngotStorage:6>, <liquid:dark.steel.molten> * 1296, 770, <EnderIO:blockIngotStorage:6>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:toolrod:171>, <liquid:dark.steel.molten> * 72, 770, <EnderIO:blockIngotStorage:6>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:pickaxeHead:171>, <liquid:dark.steel.molten> * 144, 770, <EnderIO:blockIngotStorage:6>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:shovelHead:171>, <liquid:dark.steel.molten> * 144, 770, <EnderIO:blockIngotStorage:6>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:axeHead:171>, <liquid:dark.steel.molten> * 144, 770, <EnderIO:blockIngotStorage:6>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:swordBlade:171>, <liquid:dark.steel.molten> * 144, 770, <EnderIO:blockIngotStorage:6>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:largeGuard:171>, <liquid:dark.steel.molten> * 72, 770, <EnderIO:blockIngotStorage:6>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:mediumGuard:171>, <liquid:dark.steel.molten> * 72, 770, <EnderIO:blockIngotStorage:6>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:crossbar:171>, <liquid:dark.steel.molten> * 72, 770, <EnderIO:blockIngotStorage:6>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:binding:171>, <liquid:dark.steel.molten> * 72, 770, <EnderIO:blockIngotStorage:6>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:frypanHead:171>, <liquid:dark.steel.molten> * 144, 770, <EnderIO:blockIngotStorage:6>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:battelSign:171>, <liquid:dark.steel.molten> * 144, 770, <EnderIO:blockIngotStorage:6>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:knifeBlade:171>, <liquid:dark.steel.molten> * 72, 770, <EnderIO:blockIngotStorage:6>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:chiselHead:171>, <liquid:dark.steel.molten> * 72, 770, <EnderIO:blockIngotStorage:6>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:toughrod:171>, <liquid:dark.steel.molten> * 432, 770, <EnderIO:blockIngotStorage:6>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:toughbind:171>, <liquid:dark.steel.molten> * 432, 770, <EnderIO:blockIngotStorage:6>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:largeplate:171>, <liquid:dark.steel.molten> * 1152, 770, <EnderIO:blockIngotStorage:6>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:lumberaxeHead:171>, <liquid:dark.steel.molten> * 1152, 770, <EnderIO:blockIngotStorage:6>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:scytheHead:171>, <liquid:dark.steel.molten> * 1152, 770, <EnderIO:blockIngotStorage:6>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:excavatorHead:171>, <liquid:dark.steel.molten> * 1152, 770, <EnderIO:blockIngotStorage:6>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:largeSwordBlade:171>, <liquid:dark.steel.molten> * 1152, 770, <EnderIO:blockIngotStorage:6>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:hammerHead:171>, <liquid:dark.steel.molten> * 1152, 770, <EnderIO:blockIngotStorage:6>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:fullGuard:171>, <liquid:dark.steel.molten> * 432, 770, <EnderIO:blockIngotStorage:6>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:arrowhead:171>, <liquid:dark.steel.molten> * 144, 770, <EnderIO:blockIngotStorage:6>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:shuriken:171>, <liquid:dark.steel.molten> * 72, 770, <EnderIO:blockIngotStorage:6>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:CrossbowLimb:171>, <liquid:dark.steel.molten> * 576, 770, <EnderIO:blockIngotStorage:6>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:CrossbowBody:171>, <liquid:dark.steel.molten> * 720, 770, <EnderIO:blockIngotStorage:6>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:BowLimb:171>,<liquid:dark.steel.molten> * 216, 770, <EnderIO:blockIngotStorage:6>);
mods.tconstruct.Smeltery.addMelting(<EnderIO:itemAlloy:0>, <liquid:electrical.steel.molten> * 144, 560, <EnderIO:blockIngotStorage:0>);
mods.tconstruct.Smeltery.addMelting(<EnderIO:itemAlloy:3>, <liquid:redstone.alloy.molten> * 144, 530, <EnderIO:blockIngotStorage:3>);
mods.tconstruct.Smeltery.addMelting(<EnderIO:itemAlloy:4>, <liquid:conductive.iron.molten> * 72, 550, <EnderIO:blockIngotStorage:4>);
mods.tconstruct.Smeltery.addMelting(<EnderIO:itemAlloy:7>, <liquid:soularium.molten> * 144, 170, <EnderIO:blockIngotStorage:7>);
mods.tconstruct.Smeltery.addMelting(<EnderIO:itemAlloy:1>, <liquid:energetic.alloy.molten> * 144, 580, <EnderIO:blockIngotStorage:1>);
mods.tconstruct.Smeltery.addMelting(<EnderIO:itemAlloy:5>, <liquid:phased.iron.molten> * 144, 550, <EnderIO:blockIngotStorage:5>);
mods.tconstruct.Smeltery.addMelting(<EnderIO:itemAlloy:2>, <liquid:phased.gold.molten> * 144, 600, <EnderIO:blockIngotStorage:2>);
mods.tconstruct.Smeltery.addMelting(<EnderIO:blockIngotStorage:2>, <liquid:phased.gold.molten> * 1296, 600, <EnderIO:blockIngotStorage:2>);
mods.tconstruct.Smeltery.addMelting(<EnderIO:blockIngotStorage:5>, <liquid:phased.iron.molten> * 1296, 550, <EnderIO:blockIngotStorage:5>);
mods.tconstruct.Smeltery.addMelting(<EnderIO:blockIngotStorage:0>, <liquid:electrical.steel.molten> * 1296, 560, <EnderIO:blockIngotStorage:0>);
mods.tconstruct.Smeltery.addMelting(<EnderIO:blockIngotStorage:3>, <liquid:redstone.alloy.molten> * 1296, 530, <EnderIO:blockIngotStorage:3>);
mods.tconstruct.Smeltery.addMelting(<EnderIO:blockIngotStorage:4>, <liquid:conductive.iron.molten> * 1296, 550, <EnderIO:blockIngotStorage:4>);
mods.tconstruct.Smeltery.addMelting(<EnderIO:blockIngotStorage:7>, <liquid:soularium.molten> * 1296, 170, <EnderIO:blockIngotStorage:7>);
mods.tconstruct.Smeltery.addMelting(<EnderIO:blockIngotStorage:1>, <liquid:energetic.alloy.molten> * 1296, 580, <EnderIO:blockIngotStorage:1>);

#Alloying
mods.tconstruct.Smeltery.addAlloy(<liquid:dark.steel.molten> * 36, [<liquid:iron.molten> * 36, <liquid:coal> * 25, <liquid:obsidian.molten> * 72]);
mods.tconstruct.Smeltery.addAlloy(<liquid:phased.iron.molten> * 72, [<liquid:iron.molten> * 72, <liquid:ender> * 125]);
mods.tconstruct.Smeltery.addAlloy(<liquid:phased.gold.molten> * 72, [<liquid:energetic.alloy.molten> * 72, <liquid:ender> * 125]);
mods.tconstruct.Smeltery.addAlloy(<liquid:energetic.alloy.molten> * 72, [<liquid:redstone> * 50, <liquid:gold.molten> * 72, <liquid:glowstone> * 125]);
mods.tconstruct.Smeltery.addAlloy(<liquid:conductive.iron.molten> * 35, [<liquid:redstone> * 25, <liquid:iron.molten> * 36]);

#Casting
mods.tconstruct.Casting.addTableRecipe(<EnderIO:itemAlloy:6>, <liquid:dark.steel.molten> * 144, <TConstruct:metalPattern:0>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<EnderIO:itemAlloy:0>, <liquid:electrical.steel.molten> * 144, <TConstruct:metalPattern:0>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<EnderIO:itemAlloy:3>, <liquid:redstone.alloy.molten> * 144, <TConstruct:metalPattern:0>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<EnderIO:itemAlloy:4>, <liquid:conductive.iron.molten> * 144, <TConstruct:metalPattern:0>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<EnderIO:itemAlloy:1>, <liquid:energetic.alloy.molten> * 144, <TConstruct:metalPattern:0>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<EnderIO:itemAlloy:7>, <liquid:soularium.molten> * 144, <TConstruct:metalPattern:0>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<EnderIO:itemAlloy:5>, <liquid:phased.iron.molten> * 144, <TConstruct:metalPattern:0>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<EnderIO:itemAlloy:2>, <liquid:phased.gold.molten> * 144, <TConstruct:metalPattern:0>, false, 100);
mods.tconstruct.Casting.addBasinRecipe(<EnderIO:blockIngotStorage:0>, <liquid:electrical.steel.molten> * 1296, null, false, 300);
mods.tconstruct.Casting.addBasinRecipe(<EnderIO:blockIngotStorage:1>, <liquid:energetic.alloy.molten> * 1296, null, false, 300);
mods.tconstruct.Casting.addBasinRecipe(<EnderIO:blockIngotStorage:2>, <liquid:phased.gold.molten> * 1296, null, false, 300);
mods.tconstruct.Casting.addBasinRecipe(<EnderIO:blockIngotStorage:3>, <liquid:redstone.alloy.molten> * 1296, null, false, 300);
mods.tconstruct.Casting.addBasinRecipe(<EnderIO:blockIngotStorage:4>, <liquid:conductive.iron.molten> * 1296, null, false, 300);
mods.tconstruct.Casting.addBasinRecipe(<EnderIO:blockIngotStorage:5>, <liquid:phased.iron.molten> * 1296, null, false, 300);
mods.tconstruct.Casting.addBasinRecipe(<EnderIO:blockIngotStorage:6>, <liquid:dark.steel.molten> * 1296, null, false, 300);
mods.tconstruct.Casting.addBasinRecipe(<EnderIO:blockIngotStorage:7>, <liquid:soularium.molten> * 1296, null, false, 300);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:toolrod:171>, <liquid:dark.steel.molten> * 72, <TConstruct:metalPattern:1>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:pickaxeHead:171>, <liquid:dark.steel.molten> * 144, <TConstruct:metalPattern:2>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:shovelHead:171>, <liquid:dark.steel.molten> * 144, <TConstruct:metalPattern:3>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:axeHead:171>, <liquid:dark.steel.molten> * 144, <TConstruct:metalPattern:4>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:swordBlade:171>, <liquid:dark.steel.molten> * 144, <TConstruct:metalPattern:5>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:largeGuard:171>, <liquid:dark.steel.molten> * 72, <TConstruct:metalPattern:6>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:mediumGuard:171>, <liquid:dark.steel.molten> * 72, <TConstruct:metalPattern:7>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:crossbar:171>, <liquid:dark.steel.molten> * 72, <TConstruct:metalPattern:8>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:binding:171>, <liquid:dark.steel.molten> * 72, <TConstruct:metalPattern:9>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:frypanHead:171>, <liquid:dark.steel.molten> * 144, <TConstruct:metalPattern:10>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:battelSign:171>, <liquid:dark.steel.molten> * 144, <TConstruct:metalPattern:11>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:knifeBlade:171>, <liquid:dark.steel.molten> * 72, <TConstruct:metalPattern:12>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:chiselHead:171>, <liquid:dark.steel.molten> * 72, <TConstruct:metalPattern:13>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:toughrod:171>, <liquid:dark.steel.molten> * 432, <TConstruct:metalPattern:14>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:toughbind:171>, <liquid:dark.steel.molten> * 432, <TConstruct:metalPattern:15>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:largeplate:171>, <liquid:dark.steel.molten> * 1152, <TConstruct:metalPattern:16>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:lumberaxeHead:171>, <liquid:dark.steel.molten> * 1152, <TConstruct:metalPattern:17>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:scytheHead:171>, <liquid:dark.steel.molten> * 1152, <TConstruct:metalPattern:18>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:excavatorHead:171>, <liquid:dark.steel.molten> * 1152, <TConstruct:metalPattern:19>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:largeSwordBlade:171>, <liquid:dark.steel.molten> * 1152, <TConstruct:metalPattern:20>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:hammerHead:171>, <liquid:dark.steel.molten> * 1152, <TConstruct:metalPattern:21>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:fullGuard:171>, <liquid:dark.steel.molten> * 432, <TConstruct:metalPattern:22>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:arrowhead:171>, <liquid:dark.steel.molten> * 144, <TConstruct:metalPattern:25>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:shuriken:171>, <liquid:dark.steel.molten> * 72, <TConstruct:Cast:0>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:CrossbowLimb:171>, <liquid:dark.steel.molten> * 576, <TConstruct:Cast:1>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:CrossbowBody:171>, <liquid:dark.steel.molten> * 720, <TConstruct:Cast:2>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:BowLimb:171>, <liquid:dark.steel.molten> * 216, <TConstruct:Cast:3>, false, 100);

#Melting
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:blockFunStuff:2>, <liquid:red.aurum.molten> * 1296, 850, <ExtraTiC:blockFunStuff:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:funStuffIngot:2>, <liquid:red.aurum.molten> * 144, 850, <ExtraTiC:blockFunStuff:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:toolrod:173>, <liquid:red.aurum.molten> * 72, 850, <ExtraTiC:blockFunStuff:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:pickaxeHead:173>, <liquid:red.aurum.molten> * 144, 850, <ExtraTiC:blockFunStuff:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:shovelHead:173>, <liquid:red.aurum.molten> * 144, 850, <ExtraTiC:blockFunStuff:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:axeHead:173>, <liquid:red.aurum.molten> * 144, 850, <ExtraTiC:blockFunStuff:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:swordBlade:173>, <liquid:red.aurum.molten> * 144, 850, <ExtraTiC:blockFunStuff:2>);	
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:largeGuard:173>, <liquid:red.aurum.molten> * 72, 850, <ExtraTiC:blockFunStuff:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:mediumGuard:173>, <liquid:red.aurum.molten> * 72, 850, <ExtraTiC:blockFunStuff:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:crossbar:173>, <liquid:red.aurum.molten> * 72, 850, <ExtraTiC:blockFunStuff:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:binding:173>, <liquid:red.aurum.molten> * 72, 850, <ExtraTiC:blockFunStuff:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:frypanHead:173>, <liquid:red.aurum.molten> * 144, 850, <ExtraTiC:blockFunStuff:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:battelSign:173>, <liquid:red.aurum.molten> * 144, 850, <ExtraTiC:blockFunStuff:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:knifeBlade:173>, <liquid:red.aurum.molten> * 72, 850, <ExtraTiC:blockFunStuff:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:chiselHead:173>, <liquid:red.aurum.molten> * 72, 850, <ExtraTiC:blockFunStuff:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:toughrod:173>, <liquid:red.aurum.molten> * 432, 850, <ExtraTiC:blockFunStuff:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:toughbind:173>, <liquid:red.aurum.molten> * 432, 850, <ExtraTiC:blockFunStuff:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:largeplate:173>, <liquid:red.aurum.molten> * 1152, 850, <ExtraTiC:blockFunStuff:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:lumberaxeHead:173>, <liquid:red.aurum.molten> * 1152, 850, <ExtraTiC:blockFunStuff:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:scytheHead:173>, <liquid:red.aurum.molten> * 1152, 850, <ExtraTiC:blockFunStuff:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:excavatorHead:173>, <liquid:red.aurum.molten> * 1152, 850, <ExtraTiC:blockFunStuff:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:largeSwordBlade:173>, <liquid:red.aurum.molten> * 1152, 850, <ExtraTiC:blockFunStuff:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:hammerHead:173>, <liquid:red.aurum.molten> * 1152, 850, <ExtraTiC:blockFunStuff:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:fullGuard:173>, <liquid:red.aurum.molten> * 432, 850, <ExtraTiC:blockFunStuff:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:arrowhead:173>, <liquid:red.aurum.molten> * 144, 850, <ExtraTiC:blockFunStuff:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:shuriken:173>, <liquid:red.aurum.molten> * 72, 850, <ExtraTiC:blockFunStuff:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:CrossbowLimb:173>, <liquid:red.aurum.molten> * 576, 850, <ExtraTiC:blockFunStuff:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:CrossbowBody:173>, <liquid:red.aurum.molten> * 720, 850, <ExtraTiC:blockFunStuff:2>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:BowLimb:173>, <liquid:red.aurum.molten> * 216, 850, <ExtraTiC:blockFunStuff:2>);

#Alloying
mods.tconstruct.Smeltery.addAlloy(<liquid:red.aurum.molten> * 432, [<liquid:fairy.molten> * 432, <liquid:signalum.molten> * 288, <liquid:manyullyn.molten> * 576]);

#Block and item recipes
recipes.addShapeless(<ExtraTiC:blockFunStuff:2>, [<ExtraTiC:funStuffIngot:2> * 9]);
recipes.addShapeless(<ExtraTiC:funStuffIngot:2> * 9, [<ExtraTiC:blockFunStuff:2>]);
recipes.addShaped(<TConstruct:heartCanister:5>, [[<TConstruct:diamondApple>, <ThermalFoundation:Storage:12>, <TConstruct:diamondApple>], [<ExtraTiC:blockFunStuff:2>, <TConstruct:heartCanister:3>, <ExtraTiC:blockFunStuff:2>], [<TConstruct:diamondApple>, <ThermalFoundation:Storage:12>, <TConstruct:diamondApple>]]);
recipes.addShaped(<TConstruct:heartCanister:6>, [[null, <TConstruct:heartCanister:5>, null], [<ThermalFoundation:material:38>, <TConstruct:heartCanister:4>, <ThermalFoundation:material:38>], [null, <ore:bucketEnder>, null]]);
recipes.addShaped(<TConstruct:materials:8>, [[<minecraft:coal>, <minecraft:bone>, <minecraft:coal>], [<minecraft:bone>, <minecraft:skull:1>, <minecraft:bone>], [<minecraft:coal>, <minecraft:bone>, <minecraft:coal>]]);

#Casting
mods.tconstruct.Casting.addBasinRecipe(<ExtraTiC:blockFunStuff:2>, <liquid:red.aurum.molten> * 1296, null, false, 300);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:funStuffIngot:2>, <liquid:red.aurum.molten> * 144, <TConstruct:metalPattern:0>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:toolrod:173>, <liquid:red.aurum.molten> * 72, <TConstruct:metalPattern:1>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:pickaxeHead:173>, <liquid:red.aurum.molten> * 144, <TConstruct:metalPattern:2>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:shovelHead:173>, <liquid:red.aurum.molten> * 144, <TConstruct:metalPattern:3>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:axeHead:173>, <liquid:red.aurum.molten> * 144, <TConstruct:metalPattern:4>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:swordBlade:173>, <liquid:red.aurum.molten> * 144, <TConstruct:metalPattern:5>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:largeGuard:173>, <liquid:red.aurum.molten> * 72, <TConstruct:metalPattern:6>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:mediumGuard:173>, <liquid:red.aurum.molten> * 72, <TConstruct:metalPattern:7>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:crossbar:173>, <liquid:red.aurum.molten> * 72, <TConstruct:metalPattern:8>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:binding:173>, <liquid:red.aurum.molten> * 72, <TConstruct:metalPattern:9>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:frypanHead:173>, <liquid:red.aurum.molten> * 144, <TConstruct:metalPattern:10>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:battelSign:173>, <liquid:red.aurum.molten> * 144, <TConstruct:metalPattern:11>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:knifeBlade:173>, <liquid:red.aurum.molten> * 72, <TConstruct:metalPattern:12>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:chiselHead:173>, <liquid:red.aurum.molten> * 72, <TConstruct:metalPattern:13>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:toughrod:173>, <liquid:red.aurum.molten> * 432, <TConstruct:metalPattern:14>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:toughbind:173>, <liquid:red.aurum.molten> * 432, <TConstruct:metalPattern:15>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:largeplate:173>, <liquid:red.aurum.molten> * 1152, <TConstruct:metalPattern:16>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:lumberaxeHead:173>, <liquid:red.aurum.molten> * 1152, <TConstruct:metalPattern:17>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:scytheHead:173>, <liquid:red.aurum.molten> * 1152, <TConstruct:metalPattern:18>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:excavatorHead:173>, <liquid:red.aurum.molten> * 1152, <TConstruct:metalPattern:19>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:largeSwordBlade:173>, <liquid:red.aurum.molten> * 1152, <TConstruct:metalPattern:20>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:hammerHead:173>, <liquid:red.aurum.molten> * 1152, <TConstruct:metalPattern:21>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:fullGuard:173>, <liquid:red.aurum.molten> * 432, <TConstruct:metalPattern:22>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:arrowhead:173>, <liquid:red.aurum.molten> * 144, <TConstruct:metalPattern:25>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:shuriken:173>, <liquid:red.aurum.molten> * 72, <TConstruct:Cast:0>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:CrossbowLimb:173>, <liquid:red.aurum.molten> * 576, <TConstruct:Cast:1>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:CrossbowBody:173>, <liquid:red.aurum.molten> * 720, <TConstruct:Cast:2>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:BowLimb:173>, <liquid:red.aurum.molten> * 216, <TConstruct:Cast:3>, false, 100);

#Stats
mods.tconstruct.ToolStats.setHarvestLevel("Red Aurum", 5);
mods.tconstruct.ToolStats.setDurability("Red Aurum", 800);
mods.tconstruct.ToolStats.setSpeed("Red Aurum", 1300);
mods.tconstruct.ToolStats.setDamage("Red Aurum", 10);
mods.tconstruct.ToolStats.setHandleModifier("Red Aurum", 4.376);

#Removal
mods.nei.NEI.hide(<ExtraTiC:drulloyIngot>);

#Melting
mods.tconstruct.Smeltery.addMelting(<ExtraUtilities:unstableingot>, <liquid:molten.unstableingots> * 144, 700, <ExtraUtilities:decorativeBlock1:5>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:toolRod:314>, <liquid:molten.unstableingots> * 72, 700, <ExtraUtilities:decorativeBlock1:5>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:pickaxeHead:314>, <liquid:molten.unstableingots> * 144, 700, <ExtraUtilities:decorativeBlock1:5>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:shovelHead:314>, <liquid:molten.unstableingots> * 144, 700, <ExtraUtilities:decorativeBlock1:5>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:hatchetHead:314>, <liquid:molten.unstableingots> * 144, 700, <ExtraUtilities:decorativeBlock1:5>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:swordBlade:314>, <liquid:molten.unstableingots> * 144, 700, <ExtraUtilities:decorativeBlock1:5>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:wideGuard:314>, <liquid:molten.unstableingots> * 72, 700, <ExtraUtilities:decorativeBlock1:5>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:handGuard:314>, <liquid:molten.unstableingots> * 72, 700, <ExtraUtilities:decorativeBlock1:5>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:crossbar:314>, <liquid:molten.unstableingots> * 72, 700, <ExtraUtilities:decorativeBlock1:5>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:binding:314>, <liquid:molten.unstableingots> * 72, 700, <ExtraUtilities:decorativeBlock1:5>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:frypanHead:314>, <liquid:molten.unstableingots> * 144, 700, <ExtraUtilities:decorativeBlock1:5>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:signHead:314>, <liquid:molten.unstableingots> * 144, 700, <ExtraUtilities:decorativeBlock1:5>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:knifeBlade:314>, <liquid:molten.unstableingots> * 72, 700, <ExtraUtilities:decorativeBlock1:5>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:chiselHead:314>, <liquid:molten.unstableingots> * 72, 700, <ExtraUtilities:decorativeBlock1:5>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:toughRod:314>, <liquid:molten.unstableingots> * 432, 700, <ExtraUtilities:decorativeBlock1:5>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:toughBinding:314>, <liquid:molten.unstableingots> * 432, 700, <ExtraUtilities:decorativeBlock1:5>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:heavyPlate:314>, <liquid:molten.unstableingots> * 1152, 700, <ExtraUtilities:decorativeBlock1:5>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:broadAxeHead:314>, <liquid:molten.unstableingots> * 1152, 700, <ExtraUtilities:decorativeBlock1:5>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:scytheBlade:314>, <liquid:molten.unstableingots> * 1152, 700, <ExtraUtilities:decorativeBlock1:5>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:excavatorHead:314>, <liquid:molten.unstableingots> * 1152, 700, <ExtraUtilities:decorativeBlock1:5>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:largeSwordBlade:314>, <liquid:molten.unstableingots> * 1152, 700, <ExtraUtilities:decorativeBlock1:5>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:hammerHead:314>, <liquid:molten.unstableingots> * 1152, 700, <ExtraUtilities:decorativeBlock1:5>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:arrowhead:314>, <liquid:molten.unstableingots> * 144, 700, <ExtraUtilities:decorativeBlock1:5>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:ShurikenPart:314>, <liquid:molten.unstableingots> * 72, 700, <ExtraUtilities:decorativeBlock1:5>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:CrossbowLimbPart:314>, <liquid:molten.unstableingots> * 576, 700, <ExtraUtilities:decorativeBlock1:5>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:CrossbowBodyPart:314>, <liquid:molten.unstableingots> * 720, 700, <ExtraUtilities:decorativeBlock1:5>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:BowLimbPart:314>,<liquid:molten.unstableingots> * 216, 700, <ExtraUtilities:decorativeBlock1:5>);

#Casting
mods.tconstruct.Casting.addTableRecipe(<ExtraUtilities:unstableingot>, <liquid:molten.unstableingots> * 144, <TConstruct:metalPattern:0>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:toolRod:314>, <liquid:molten.unstableingots> * 72, <TConstruct:metalPattern:1>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:pickaxeHead:314>, <liquid:molten.unstableingots> * 144, <TConstruct:metalPattern:2>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:shovelHead:314>, <liquid:molten.unstableingots> * 144, <TConstruct:metalPattern:3>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:hatchetHead:314>, <liquid:molten.unstableingots> * 144, <TConstruct:metalPattern:4>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:swordBlade:314>, <liquid:molten.unstableingots> * 144, <TConstruct:metalPattern:5>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:wideGuard:314>, <liquid:molten.unstableingots> * 72, <TConstruct:metalPattern:6>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:handGuard:314>, <liquid:molten.unstableingots> * 72, <TConstruct:metalPattern:7>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:crossbar:314>, <liquid:molten.unstableingots> * 72, <TConstruct:metalPattern:8>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:binding:314>, <liquid:molten.unstableingots> * 72, <TConstruct:metalPattern:9>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:frypanHead:314>, <liquid:molten.unstableingots> * 144, <TConstruct:metalPattern:10>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:signHead:314>, <liquid:molten.unstableingots> * 144, <TConstruct:metalPattern:11>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:knifeBlade:314>, <liquid:molten.unstableingots> * 72, <TConstruct:metalPattern:12>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:chiselHead:314>, <liquid:molten.unstableingots> * 72, <TConstruct:metalPattern:13>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:toughRod:314>, <liquid:molten.unstableingots> * 432, <TConstruct:metalPattern:14>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:toughBinding:314>, <liquid:molten.unstableingots> * 432, <TConstruct:metalPattern:15>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:heavyPlate:314>, <liquid:molten.unstableingots> * 1152, <TConstruct:metalPattern:16>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:broadAxeHead:314>, <liquid:molten.unstableingots> * 1152, <TConstruct:metalPattern:17>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:scytheBlade:314>, <liquid:molten.unstableingots> * 1152, <TConstruct:metalPattern:18>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:excavatorHead:314>, <liquid:molten.unstableingots> * 1152, <TConstruct:metalPattern:19>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:largeSwordBlade:314>, <liquid:molten.unstableingots> * 1152, <TConstruct:metalPattern:20>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:hammerHead:314>, <liquid:molten.unstableingots> * 1152, <TConstruct:metalPattern:21>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:arrowhead:314>, <liquid:molten.unstableingots> * 144, <TConstruct:metalPattern:25>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:ShurikenPart:314>, <liquid:molten.unstableingots> * 72, <TConstruct:Cast:0>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:CrossbowLimbPart:314>, <liquid:molten.unstableingots> * 576, <TConstruct:Cast:1>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:CrossbowBodyPart:314>, <liquid:molten.unstableingots> * 720, <TConstruct:Cast:2>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:BowLimbPart:314>,<liquid:molten.unstableingots> * 216, <TConstruct:Cast:3>, false, 100);

#Removal
mods.tconstruct.Casting.removeTableRecipe(<TConstruct:toolRod:315>);
mods.tconstruct.Casting.removeTableRecipe(<TConstruct:swordBlade:315>);
mods.tconstruct.Casting.removeTableRecipe(<TConstruct:wideGuard:315>);
mods.tconstruct.Casting.removeTableRecipe(<TConstruct:handGuard:315>);
mods.tconstruct.Casting.removeTableRecipe(<TConstruct:crossbar:315>);
mods.tconstruct.Casting.removeTableRecipe(<TConstruct:frypanHead:315>);
mods.tconstruct.Casting.removeTableRecipe(<TConstruct:knifeBlade:315>);
mods.tconstruct.Casting.removeTableRecipe(<TConstruct:signHead:315>);
mods.tconstruct.Casting.removeTableRecipe(<TConstruct:chiselHead:315>);
mods.tconstruct.Casting.removeTableRecipe(<TConstruct:scytheBlade:315>);
mods.tconstruct.Casting.removeTableRecipe(<TConstruct:broadAxeHead:315>);
mods.tconstruct.Casting.removeTableRecipe(<TConstruct:excavatorHead:315>);
mods.tconstruct.Casting.removeTableRecipe(<TConstruct:largeSwordBlade:315>);
mods.tconstruct.Casting.removeTableRecipe(<TConstruct:hammerHead:315>);
mods.tconstruct.Casting.removeTableRecipe(<TConstruct:arrowhead:315>);
mods.tconstruct.Casting.removeTableRecipe(<TConstruct:ShurikenPart:315>);
mods.tconstruct.Casting.removeTableRecipe(<TConstruct:BowLimbPart:315>);
mods.tconstruct.Casting.removeTableRecipe(<TConstruct:CrossbowBodyPart:315>);
mods.tconstruct.Casting.removeTableRecipe(<TConstruct:CrossbowLimbPart:315>);
mods.tconstruct.Casting.removeTableRecipe(<TConstruct:BoltPart:315>.withTag({DualMat: {Material2: 2}}));
mods.tconstruct.Casting.removeTableRecipe(<TConstruct:pickaxeHead:315>);
mods.tconstruct.Casting.removeTableRecipe(<TConstruct:shovelHead:315>);
mods.tconstruct.Casting.removeTableRecipe(<TConstruct:hatchetHead:315>);
mods.tconstruct.Casting.removeTableRecipe(<TConstruct:toughBinding:315>);
mods.tconstruct.Casting.removeTableRecipe(<TConstruct:toughRod:315>);
mods.tconstruct.Casting.removeTableRecipe(<TConstruct:binding:315>);
mods.tconstruct.Casting.removeTableRecipe(<TConstruct:heavyPlate:315>);
mods.tconstruct.Casting.removeTableRecipe(<TConstruct:BoltPart:185>.withTag({DualMat: {Material2: 2}}));

mods.nei.NEI.hide(<TConstruct:toolRod:315>);
mods.nei.NEI.hide(<TConstruct:swordBlade:315>);
mods.nei.NEI.hide(<TConstruct:wideGuard:315>);
mods.nei.NEI.hide(<TConstruct:handGuard:315>);
mods.nei.NEI.hide(<TConstruct:crossbar:315>);
mods.nei.NEI.hide(<TConstruct:frypanHead:315>);
mods.nei.NEI.hide(<TConstruct:knifeBlade:315>);
mods.nei.NEI.hide(<TConstruct:signHead:315>);
mods.nei.NEI.hide(<TConstruct:chiselHead:315>);
mods.nei.NEI.hide(<TConstruct:scytheBlade:315>);
mods.nei.NEI.hide(<TConstruct:broadAxeHead:315>);
mods.nei.NEI.hide(<TConstruct:excavatorHead:315>);
mods.nei.NEI.hide(<TConstruct:largeSwordBlade:315>);
mods.nei.NEI.hide(<TConstruct:hammerHead:315>);
mods.nei.NEI.hide(<TConstruct:arrowhead:315>);
mods.nei.NEI.hide(<TConstruct:ShurikenPart:315>);
mods.nei.NEI.hide(<TConstruct:BowLimbPart:315>);
mods.nei.NEI.hide(<TConstruct:CrossbowBodyPart:315>);
mods.nei.NEI.hide(<TConstruct:CrossbowLimbPart:315>);
mods.nei.NEI.hide(<TConstruct:BoltPart:315>.withTag({DualMat: {Material2: 2}}));
mods.nei.NEI.hide(<TConstruct:pickaxeHead:315>);
mods.nei.NEI.hide(<TConstruct:shovelHead:315>);
mods.nei.NEI.hide(<TConstruct:hatchetHead:315>);
mods.nei.NEI.hide(<TConstruct:toughBinding:315>);
mods.nei.NEI.hide(<TConstruct:toughRod:315>);
mods.nei.NEI.hide(<TConstruct:binding:315>);
mods.nei.NEI.hide(<TConstruct:heavyPlate:315>);
mods.nei.NEI.hide(<TConstruct:toolShard:315>);
mods.nei.NEI.hide(<TConstruct:BoltPart:185>.withTag({DualMat: {Material2: 2}}));

mods.nei.NEI.hide(<TConstruct:pickaxe>.withTag({InfiTool: {BaseDurability: 13125, Head: 315, BaseAttack: 5, Built: 1 as byte, HarvestLevel: 7, Attack: 5, RenderHead: 315, ModDurability: 0.0 as float, Handle: 315, Broken: 0 as byte, Shoddy: 0.0 as float, RenderHandle: 315, Accessory: 315, MiningSpeed: 800, RenderAccessory: 315, Unbreaking: 0, Damage: 0, BonusDurability: 0, TotalDurability: 13125, Modifiers: 3}, display: {Name: "§fBedrockium Pickaxe"}, AttributeModifiers: [{UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: -0.30000000000000004, AttributeName: "generic.movementSpeed", Operation: 2, Name: "[TCon]Bedrockium Weight"}, {UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: 1.5, AttributeName: "generic.knockbackResistance", Operation: 2, Name: "[TCon]Bedrockium Weight"}]}));
mods.nei.NEI.hide(<TConstruct:shovel>.withTag({InfiTool: {BaseDurability: 13125, Head: 315, BaseAttack: 6, Built: 1 as byte, HarvestLevel: 7, Attack: 6, RenderHead: 315, ModDurability: 0.0 as float, Handle: 315, Broken: 0 as byte, Shoddy: 0.0 as float, RenderHandle: 315, MiningSpeed: 800, Unbreaking: 0, Damage: 0, BonusDurability: 0, TotalDurability: 13125, Modifiers: 3}, display: {Name: "§fBedrockium Shovel"}, AttributeModifiers: [{UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: -0.2, AttributeName: "generic.movementSpeed", Operation: 2, Name: "[TCon]Bedrockium Weight"}, {UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: 1.0, AttributeName: "generic.knockbackResistance", Operation: 2, Name: "[TCon]Bedrockium Weight"}]}));
mods.nei.NEI.hide(<TConstruct:hatchet>.withTag({InfiTool: {BaseDurability: 13125, Head: 315, BaseAttack: 7, Built: 1 as byte, HarvestLevel: 7, Attack: 7, RenderHead: 315, ModDurability: 0.0 as float, Handle: 315, Broken: 0 as byte, Shoddy: 0.0 as float, RenderHandle: 315, MiningSpeed: 800, Unbreaking: 0, Damage: 0, BonusDurability: 0, TotalDurability: 13125, Modifiers: 3}, display: {Name: "§fBedrockium Hatchet"}, AttributeModifiers: [{UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: -0.2, AttributeName: "generic.movementSpeed", Operation: 2, Name: "[TCon]Bedrockium Weight"}, {UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: 1.0, AttributeName: "generic.knockbackResistance", Operation: 2, Name: "[TCon]Bedrockium Weight"}]}));
mods.nei.NEI.hide(<TConstruct:broadsword>.withTag({InfiTool: {BaseDurability: 15750, Head: 315, BaseAttack: 8, Built: 1 as byte, HarvestLevel: 7, Attack: 8, RenderHead: 315, ModDurability: 0.0 as float, Handle: 315, Broken: 0 as byte, Shoddy: 0.0 as float, RenderHandle: 315, Accessory: 315, MiningSpeed: 800, RenderAccessory: 315, Unbreaking: 0, Damage: 0, BonusDurability: 0, TotalDurability: 15750, Modifiers: 3}, display: {Name: "§fBedrockium Broadsword"}, AttributeModifiers: [{UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: -0.30000000000000004, AttributeName: "generic.movementSpeed", Operation: 2, Name: "[TCon]Bedrockium Weight"}, {UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: 1.5, AttributeName: "generic.knockbackResistance", Operation: 2, Name: "[TCon]Bedrockium Weight"}]}));
mods.nei.NEI.hide(<TConstruct:longsword>.withTag({InfiTool: {BaseDurability: 13125, Head: 315, BaseAttack: 8, Built: 1 as byte, HarvestLevel: 7, Attack: 8, RenderHead: 315, ModDurability: 0.0 as float, Handle: 315, Broken: 0 as byte, Shoddy: 0.0 as float, RenderHandle: 315, Accessory: 315, MiningSpeed: 800, RenderAccessory: 315, Unbreaking: 0, Damage: 0, BonusDurability: 0, TotalDurability: 13125, Modifiers: 3}, display: {Name: "§fBedrockium Longsword"}, AttributeModifiers: [{UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: -0.30000000000000004, AttributeName: "generic.movementSpeed", Operation: 2, Name: "[TCon]Bedrockium Weight"}, {UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: 1.5, AttributeName: "generic.knockbackResistance", Operation: 2, Name: "[TCon]Bedrockium Weight"}]}));
mods.nei.NEI.hide(<TConstruct:rapier>.withTag({InfiTool: {BaseDurability: 9187, Head: 315, BaseAttack: 6, Built: 1 as byte, HarvestLevel: 7, Attack: 6, RenderHead: 315, ModDurability: 0.0 as float, Handle: 315, Broken: 0 as byte, Shoddy: 0.0 as float, RenderHandle: 315, Accessory: 315, MiningSpeed: 800, RenderAccessory: 315, Unbreaking: 0, Damage: 0, BonusDurability: 0, TotalDurability: 9187, Modifiers: 3}, display: {Name: "§fBedrockium Rapier"}, AttributeModifiers: [{UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: -0.30000000000000004, AttributeName: "generic.movementSpeed", Operation: 2, Name: "[TCon]Bedrockium Weight"}, {UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: 1.5, AttributeName: "generic.knockbackResistance", Operation: 2, Name: "[TCon]Bedrockium Weight"}]}));
mods.nei.NEI.hide(<TConstruct:dagger>.withTag({InfiTool: {BaseDurability: 13125, Head: 315, BaseAttack: 5, Built: 1 as byte, HarvestLevel: 7, Attack: 5, RenderHead: 315, ModDurability: 0.0 as float, Handle: 315, Broken: 0 as byte, Shoddy: 0.0 as float, RenderHandle: 315, Accessory: 315, MiningSpeed: 800, RenderAccessory: 315, Unbreaking: 0, Damage: 0, BonusDurability: 0, TotalDurability: 13125, Modifiers: 3}, display: {Name: "§fBedrockium Dagger"}, AttributeModifiers: [{UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: -0.30000000000000004, AttributeName: "generic.movementSpeed", Operation: 2, Name: "[TCon]Bedrockium Weight"}, {UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: 1.5, AttributeName: "generic.knockbackResistance", Operation: 2, Name: "[TCon]Bedrockium Weight"}]}));
mods.nei.NEI.hide(<TConstruct:cutlass>.withTag({InfiTool: {BaseDurability: 19687, Head: 315, BaseAttack: 8, Built: 1 as byte, HarvestLevel: 7, Attack: 8, RenderHead: 315, ModDurability: 0.0 as float, Handle: 315, Broken: 0 as byte, Shoddy: 0.0 as float, RenderHandle: 315, Accessory: 315, MiningSpeed: 800, RenderAccessory: 315, Unbreaking: 0, Damage: 0, BonusDurability: 0, TotalDurability: 19687, Modifiers: 3}, display: {Name: "§fBedrockium Cutlass"}, AttributeModifiers: [{UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: -0.30000000000000004, AttributeName: "generic.movementSpeed", Operation: 2, Name: "[TCon]Bedrockium Weight"}, {UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: 1.5, AttributeName: "generic.knockbackResistance", Operation: 2, Name: "[TCon]Bedrockium Weight"}]}));
mods.nei.NEI.hide(<TConstruct:frypan>.withTag({InfiTool: {BaseDurability: 13125, Head: 315, BaseAttack: 6, Built: 1 as byte, HarvestLevel: 7, Attack: 6, RenderHead: 315, ModDurability: 0.0 as float, Handle: 315, Broken: 0 as byte, Shoddy: 0.0 as float, RenderHandle: 315, MiningSpeed: 800, Unbreaking: 0, Damage: 0, BonusDurability: 0, TotalDurability: 13125, Modifiers: 3}, display: {Name: "§fBedrockium Frying Pan"}, AttributeModifiers: [{UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: -0.2, AttributeName: "generic.movementSpeed", Operation: 2, Name: "[TCon]Bedrockium Weight"}, {UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: 1.0, AttributeName: "generic.knockbackResistance", Operation: 2, Name: "[TCon]Bedrockium Weight"}]}));
mods.nei.NEI.hide(<TConstruct:battlesign>.withTag({InfiTool: {BaseDurability: 13125, Head: 315, BaseAttack: 5, Built: 1 as byte, HarvestLevel: 7, Attack: 5, RenderHead: 315, ModDurability: 0.0 as float, Handle: 315, Broken: 0 as byte, Shoddy: 0.0 as float, RenderHandle: 315, MiningSpeed: 800, Unbreaking: 0, Damage: 0, BonusDurability: 0, TotalDurability: 13125, Modifiers: 4}, display: {Name: "§fBedrockium Battle Sign"}, AttributeModifiers: [{UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: -0.2, AttributeName: "generic.movementSpeed", Operation: 2, Name: "[TCon]Bedrockium Weight"}, {UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: 1.0, AttributeName: "generic.knockbackResistance", Operation: 2, Name: "[TCon]Bedrockium Weight"}]}));
mods.nei.NEI.hide(<TConstruct:mattock>.withTag({InfiTool: {MiningSpeed2: 800, BaseDurability: 19687, Head: 315, BaseAttack: 8, Built: 1 as byte, HarvestLevel: 7, Attack: 8, RenderHead: 315, ModDurability: 0.0 as float, Handle: 315, Broken: 0 as byte, Shoddy: 0.0 as float, RenderHandle: 315, Accessory: 315, MiningSpeed: 800, RenderAccessory: 315, Unbreaking: 0, Damage: 0, HarvestLevel2: 7, BonusDurability: 0, TotalDurability: 19687, Modifiers: 3}, display: {Name: "§fBedrockium Mattock"}, AttributeModifiers: [{UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: -0.30000000000000004, AttributeName: "generic.movementSpeed", Operation: 2, Name: "[TCon]Bedrockium Weight"}, {UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: 1.5, AttributeName: "generic.knockbackResistance", Operation: 2, Name: "[TCon]Bedrockium Weight"}]}));
mods.nei.NEI.hide(<TConstruct:chisel>.withTag({InfiTool: {BaseDurability: 13125, Head: 315, BaseAttack: 4, Built: 1 as byte, HarvestLevel: 7, Attack: 4, RenderHead: 315, ModDurability: 0.0 as float, Handle: 315, Broken: 0 as byte, Shoddy: 0.0 as float, RenderHandle: 315, MiningSpeed: 800, Unbreaking: 0, Damage: 0, BonusDurability: 0, TotalDurability: 13125, Modifiers: 3}, display: {Name: "§fBedrockium Chisel"}, AttributeModifiers: [{UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: -0.2, AttributeName: "generic.movementSpeed", Operation: 2, Name: "[TCon]Bedrockium Weight"}, {UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: 1.0, AttributeName: "generic.knockbackResistance", Operation: 2, Name: "[TCon]Bedrockium Weight"}]}));
mods.nei.NEI.hide(<TConstruct:lumberaxe>.withTag({InfiTool: {RenderExtra: 315, MiningSpeed2: 800, BaseDurability: 73828, Head: 315, BaseAttack: 4, Built: 1 as byte, HarvestLevel: 7, Attack: 4, RenderHead: 315, ModDurability: 0.0 as float, Handle: 315, Broken: 0 as byte, Shoddy: 0.0 as float, RenderHandle: 315, Accessory: 315, Extra: 315, MiningSpeed: 800, RenderAccessory: 315, Unbreaking: 0, Damage: 0, HarvestLevel2: 7, BonusDurability: 0, TotalDurability: 73828, Modifiers: 3}, display: {Name: "§fBedrockium Lumber Axe"}, AttributeModifiers: [{UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: -0.4, AttributeName: "generic.movementSpeed", Operation: 2, Name: "[TCon]Bedrockium Weight"}, {UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: 2.0, AttributeName: "generic.knockbackResistance", Operation: 2, Name: "[TCon]Bedrockium Weight"}]}));
mods.nei.NEI.hide(<TConstruct:cleaver>.withTag({InfiTool: {RenderExtra: 315, MiningSpeed2: 800, BaseDurability: 73828, Head: 315, BaseAttack: 10, Built: 1 as byte, HarvestLevel: 7, Attack: 10, RenderHead: 315, ModDurability: 0.0 as float, Handle: 315, Broken: 0 as byte, Shoddy: 0.0 as float, RenderHandle: 315, Accessory: 315, Extra: 315, MiningSpeed: 800, RenderAccessory: 315, Unbreaking: 0, Damage: 0, HarvestLevel2: 7, BonusDurability: 0, TotalDurability: 73828, Modifiers: 3}, display: {Name: "§fBedrockium Cleaver"}, AttributeModifiers: [{UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: -0.4, AttributeName: "generic.movementSpeed", Operation: 2, Name: "[TCon]Bedrockium Weight"}, {UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: 2.0, AttributeName: "generic.knockbackResistance", Operation: 2, Name: "[TCon]Bedrockium Weight"}]}));
mods.nei.NEI.hide(<TConstruct:scythe>.withTag({InfiTool: {RenderExtra: 315, BaseDurability: 78750, Head: 315, BaseAttack: 8, Built: 1 as byte, HarvestLevel: 7, Attack: 8, RenderHead: 315, ModDurability: 0.0 as float, Handle: 315, Broken: 0 as byte, Shoddy: 0.0 as float, RenderHandle: 315, Accessory: 315, Extra: 315, MiningSpeed: 800, RenderAccessory: 315, Unbreaking: 0, Damage: 0, BonusDurability: 0, TotalDurability: 78750, Modifiers: 3}, display: {Name: "§fBedrockium Scythe"}, AttributeModifiers: [{UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: -0.4, AttributeName: "generic.movementSpeed", Operation: 2, Name: "[TCon]Bedrockium Weight"}, {UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: 2.0, AttributeName: "generic.knockbackResistance", Operation: 2, Name: "[TCon]Bedrockium Weight"}]}));
mods.nei.NEI.hide(<TConstruct:excavator>.withTag({InfiTool: {RenderExtra: 315, MiningSpeed2: 800, BaseDurability: 81210, Head: 315, BaseAttack: 6, Built: 1 as byte, HarvestLevel: 7, Attack: 6, RenderHead: 315, ModDurability: 0.0 as float, Handle: 315, Broken: 0 as byte, Shoddy: 0.0 as float, RenderHandle: 315, Accessory: 315, Extra: 315, MiningSpeed: 800, RenderAccessory: 315, Unbreaking: 0, Damage: 0, HarvestLevel2: 7, BonusDurability: 0, TotalDurability: 81210, Modifiers: 3}, display: {Name: "§fBedrockium Excavator"}, AttributeModifiers: [{UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: -0.4, AttributeName: "generic.movementSpeed", Operation: 2, Name: "[TCon]Bedrockium Weight"}, {UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: 2.0, AttributeName: "generic.knockbackResistance", Operation: 2, Name: "[TCon]Bedrockium Weight"}]}));
mods.nei.NEI.hide(<TConstruct:hammer>.withTag({InfiTool: {RenderExtra: 315, BaseDurability: 118125, BaseAttack: 6, Built: 1 as byte, HarvestLevel: 7, HarvestLevelExtra: 7, RenderHead: 315, ModDurability: 0.0 as float, MiningSpeedExtra: 800, Shoddy: 0.0 as float, RenderHandle: 315, Accessory: 315, MiningSpeed: 800, Unbreaking: 0, Damage: 0, HarvestLevel2: 7, BonusDurability: 0, TotalDurability: 118125, MiningSpeed2: 800, Head: 315, Attack: 6, Handle: 315, Broken: 0 as byte, Extra: 315, RenderAccessory: 315, Modifiers: 3}, display: {Name: "§fBedrockium Hammer"}, AttributeModifiers: [{UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: -0.4, AttributeName: "generic.movementSpeed", Operation: 2, Name: "[TCon]Bedrockium Weight"}, {UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: 2.0, AttributeName: "generic.knockbackResistance", Operation: 2, Name: "[TCon]Bedrockium Weight"}]}));
mods.nei.NEI.hide(<TConstruct:battleaxe>.withTag({InfiTool: {RenderExtra: 315, MiningSpeed2: 800, BaseDurability: 73828, Head: 315, BaseAttack: 8, Built: 1 as byte, HarvestLevel: 7, Attack: 8, RenderHead: 315, ModDurability: 0.0 as float, Handle: 315, Broken: 0 as byte, Shoddy: 0.0 as float, RenderHandle: 315, Accessory: 315, Extra: 315, MiningSpeed: 800, RenderAccessory: 315, Unbreaking: 0, Damage: 0, HarvestLevel2: 7, BonusDurability: 0, TotalDurability: 73828, Modifiers: 3}, display: {Name: "§fBedrockium Battleaxe"}, AttributeModifiers: [{UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: -0.4, AttributeName: "generic.movementSpeed", Operation: 2, Name: "[TCon]Bedrockium Weight"}, {UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: 2.0, AttributeName: "generic.knockbackResistance", Operation: 2, Name: "[TCon]Bedrockium Weight"}]}));
mods.nei.NEI.hide(<TConstruct:Shuriken>.withTag({InfiTool: {RenderExtra: 315, BaseDurability: 18750, BaseAttack: 6, Built: 1 as byte, HarvestLevel: 7, HarvestLevelExtra: 7, RenderHead: 315, ModDurability: 0.0 as float, MiningSpeedExtra: 800, Shoddy: 0.0 as float, RenderHandle: 315, Accessory: 315, MiningSpeed: 800, MiningSpeedHandle: 800, Unbreaking: 0, Damage: 0, HarvestLevel2: 7, BonusDurability: 0, TotalDurability: 18750, MiningSpeed2: 800, Head: 315, HarvestLevelHandle: 7, Attack: 6, Handle: 315, Broken: 0 as byte, Ammo: 1875, Extra: 315, RenderAccessory: 315, Modifiers: 3}, display: {Name: "§fBedrockium Shuriken"}, AttributeModifiers: [{UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: -0.4, AttributeName: "generic.movementSpeed", Operation: 2, Name: "[TCon]Bedrockium Weight"}, {UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: 2.0, AttributeName: "generic.knockbackResistance", Operation: 2, Name: "[TCon]Bedrockium Weight"}]}));
mods.nei.NEI.hide(<TConstruct:ThrowingKnife>.withTag({InfiTool: {BaseDurability: 13125, Head: 315, BaseAttack: 5, Built: 1 as byte, HarvestLevel: 7, Attack: 5, RenderHead: 315, ModDurability: 0.0 as float, Handle: 315, Broken: 0 as byte, Shoddy: 0.0 as float, RenderHandle: 315, Ammo: 1313, MiningSpeed: 800, Unbreaking: 0, Damage: 0, BonusDurability: 0, TotalDurability: 13125, Modifiers: 3}, display: {Name: "§fBedrockium Throwing Knife"}, AttributeModifiers: [{UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: -0.2, AttributeName: "generic.movementSpeed", Operation: 2, Name: "[TCon]Bedrockium Weight"}, {UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: 1.0, AttributeName: "generic.knockbackResistance", Operation: 2, Name: "[TCon]Bedrockium Weight"}]}));
mods.nei.NEI.hide(<TConstruct:Javelin>.withTag({InfiTool: {BaseDurability: 1312, Head: 315, BaseAttack: 7, Built: 1 as byte, HarvestLevel: 7, Attack: 7, RenderHead: 315, ModDurability: 0.0 as float, Handle: 315, Broken: 0 as byte, Shoddy: 0.0 as float, RenderHandle: 315, Ammo: 263, Accessory: 315, MiningSpeed: 800, RenderAccessory: 315, Unbreaking: 0, Damage: 0, BonusDurability: 0, TotalDurability: 1312, Modifiers: 3}, display: {Name: "§fBedrockium Javelin"}, AttributeModifiers: [{UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: -0.30000000000000004, AttributeName: "generic.movementSpeed", Operation: 2, Name: "[TCon]Bedrockium Weight"}, {UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: 1.5, AttributeName: "generic.knockbackResistance", Operation: 2, Name: "[TCon]Bedrockium Weight"}]}));
mods.nei.NEI.hide(<TConstruct:ShortBow>.withTag({InfiTool: {BaseDurability: 11250, BaseAttack: 4, DrawSpeed: 180, Built: 1 as byte, HarvestLevel: 7, RenderHead: 315, ModDurability: 0.0 as float, Shoddy: 0.0 as float, RenderHandle: 0, Accessory: 315, MiningSpeed: 800, Unbreaking: 0, Damage: 0, HarvestLevel2: 7, BonusDurability: 0, TotalDurability: 11250, MiningSpeed2: 800, BaseDrawSpeed: 180, Head: 315, Attack: 4, Handle: 0, Broken: 0 as byte, RenderAccessory: 315, FlightSpeed: 3.0 as float, Modifiers: 3}, display: {Name: "§fBedrockium Shortbow"}, AttributeModifiers: [{UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: -0.2, AttributeName: "generic.movementSpeed", Operation: 2, Name: "[TCon]Bedrockium Weight"}, {UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: 1.0, AttributeName: "generic.knockbackResistance", Operation: 2, Name: "[TCon]Bedrockium Weight"}]}));
mods.nei.NEI.hide(<TConstruct:LongBow>.withTag({InfiTool: {RenderExtra: 315, BaseDurability: 23203, BaseAttack: 4, DrawSpeed: 360, Built: 1 as byte, HarvestLevel: 7, RenderHead: 315, ModDurability: 0.0 as float, Shoddy: 0.0 as float, RenderHandle: 0, Accessory: 315, MiningSpeed: 800, Unbreaking: 0, Damage: 0, HarvestLevel2: 7, BonusDurability: 0, TotalDurability: 23203, MiningSpeed2: 800, BaseDrawSpeed: 360, Head: 315, Attack: 4, Handle: 0, Broken: 0 as byte, Extra: 315, RenderAccessory: 315, FlightSpeed: 4.5 as float, Modifiers: 3}, display: {Name: "§fBedrockium Longbow"}, AttributeModifiers: [{UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: -0.30000000000000004, AttributeName: "generic.movementSpeed", Operation: 2, Name: "[TCon]Bedrockium Weight"}, {UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: 1.5, AttributeName: "generic.knockbackResistance", Operation: 2, Name: "[TCon]Bedrockium Weight"}]}));
mods.nei.NEI.hide(<TConstruct:Crossbow>.withTag({InfiTool: {RenderExtra: 315, BaseDurability: 13125, BaseAttack: 4, DrawSpeed: 375, Built: 1 as byte, HarvestLevel: 7, RenderHead: 315, ModDurability: 0.0 as float, Shoddy: 0.0 as float, RenderHandle: 315, Accessory: 0, MiningSpeed: 800, Unbreaking: 0, Damage: 0, BonusDurability: 0, TotalDurability: 13125, BaseDrawSpeed: 375, Head: 315, Attack: 4, Handle: 315, Broken: 0 as byte, Extra: 315, RenderAccessory: 0, FlightSpeed: 4.5 as float, Modifiers: 3}, display: {Name: "§fBedrockium Crossbow"}, AttributeModifiers: [{UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: -0.30000000000000004, AttributeName: "generic.movementSpeed", Operation: 2, Name: "[TCon]Bedrockium Weight"}, {UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: 1.5, AttributeName: "generic.knockbackResistance", Operation: 2, Name: "[TCon]Bedrockium Weight"}]}));
mods.nei.NEI.hide(<TConstruct:ArrowAmmo>.withTag({InfiTool: {BreakChance: 0.11 as float, BaseDurability: 7500, Head: 315, BaseAttack: 4, Built: 1 as byte, HarvestLevel: 7, Attack: 4, RenderHead: 315, ModDurability: 0.0 as float, Handle: 0, Broken: 0 as byte, Shoddy: 0.0 as float, Mass: 41.0 as float, RenderHandle: 0, Ammo: 750, Accuracy: 95.0 as float, Accessory: 0, MiningSpeed: 800, RenderAccessory: 0, Unbreaking: 0, Damage: 0, BonusDurability: 0, TotalDurability: 7500, Modifiers: 2}, display: {Name: "§fBedrockium Arrows"}, AttributeModifiers: [{UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: -0.1, AttributeName: "generic.movementSpeed", Operation: 2, Name: "[TCon]Bedrockium Weight"}, {UUIDMost: 5965584238583157221 as long, UUIDLeast: -6431115425909183365 as long, Amount: 0.5, AttributeName: "generic.knockbackResistance", Operation: 2, Name: "[TCon]Bedrockium Weight"}]}));

#Melting
mods.tconstruct.Smeltery.addMelting(<Thaumcraft:ItemResource:16>, <liquid:voidmetal.molten> * 144, 500, <Thaumcraft:ItemResource:16>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:toolrod:172>, <liquid:voidmetal.molten> * 72, 500, <Thaumcraft:ItemResource:16>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:pickaxeHead:172>, <liquid:voidmetal.molten> * 144, 500, <Thaumcraft:ItemResource:16>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:shovelHead:172>, <liquid:voidmetal.molten> * 144, 500, <Thaumcraft:ItemResource:16>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:axeHead:172>, <liquid:voidmetal.molten> * 144, 500, <Thaumcraft:ItemResource:16>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:swordBlade:172>, <liquid:voidmetal.molten> * 144, 500, <Thaumcraft:ItemResource:16>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:largeGuard:172>, <liquid:voidmetal.molten> * 72, 500, <Thaumcraft:ItemResource:16>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:mediumGuard:172>, <liquid:voidmetal.molten> * 72, 500, <Thaumcraft:ItemResource:16>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:crossbar:172>, <liquid:voidmetal.molten> * 72, 500, <Thaumcraft:ItemResource:16>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:binding:172>, <liquid:voidmetal.molten> * 72, 500, <Thaumcraft:ItemResource:16>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:frypanHead:172>, <liquid:voidmetal.molten> * 144, 500, <Thaumcraft:ItemResource:16>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:battelSign:172>, <liquid:voidmetal.molten> * 144, 500, <Thaumcraft:ItemResource:16>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:knifeBlade:172>, <liquid:voidmetal.molten> * 72, 500, <Thaumcraft:ItemResource:16>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:chiselHead:172>, <liquid:voidmetal.molten> * 72, 500, <Thaumcraft:ItemResource:16>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:toughrod:172>, <liquid:voidmetal.molten> * 432, 500, <Thaumcraft:ItemResource:16>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:toughbind:172>, <liquid:voidmetal.molten> * 432, 500, <Thaumcraft:ItemResource:16>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:largeplate:172>, <liquid:voidmetal.molten> * 1152, 500, <Thaumcraft:ItemResource:16>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:lumberaxeHead:172>, <liquid:voidmetal.molten> * 1152, 500, <Thaumcraft:ItemResource:16>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:scytheHead:172>, <liquid:voidmetal.molten> * 1152, 500, <Thaumcraft:ItemResource:16>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:excavatorHead:172>, <liquid:voidmetal.molten> * 1152, 500, <Thaumcraft:ItemResource:16>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:largeSwordBlade:172>, <liquid:voidmetal.molten> * 1152, 500, <Thaumcraft:ItemResource:16>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:hammerHead:172>, <liquid:voidmetal.molten> * 1152, 500, <Thaumcraft:ItemResource:16>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:fullGuard:172>, <liquid:voidmetal.molten> * 432, 500, <Thaumcraft:ItemResource:16>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:arrowhead:172>, <liquid:voidmetal.molten> * 144, 500, <Thaumcraft:ItemResource:16>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:shuriken:172>, <liquid:voidmetal.molten> * 72, 500, <Thaumcraft:ItemResource:16>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:CrossbowLimb:172>, <liquid:voidmetal.molten> * 576, 500, <Thaumcraft:ItemResource:16>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:CrossbowBody:172>, <liquid:voidmetal.molten> * 720, 500, <Thaumcraft:ItemResource:16>);
mods.tconstruct.Smeltery.addMelting(<ExtraTiC:BowLimb:172>, <liquid:voidmetal.molten> * 216, 500, <Thaumcraft:ItemResource:16>);

mods.tconstruct.Smeltery.addMelting(<Thaumcraft:blockCosmeticSolid:4>, <liquid:mana> * 1296, 500, <Thaumcraft:blockCosmeticSolid:4>);
mods.tconstruct.Smeltery.addMelting(<Thaumcraft:ItemResource:2>, <liquid:mana> * 144, 500, <Thaumcraft:blockCosmeticSolid:4>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:toolRod:31>, <liquid:mana> * 72, 500, <Thaumcraft:blockCosmeticSolid:4>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:pickaxeHead:31>, <liquid:mana> * 144, 500, <Thaumcraft:blockCosmeticSolid:4>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:shovelHead:31>, <liquid:mana> * 144, 500, <Thaumcraft:blockCosmeticSolid:4>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:hatchetHead:31>, <liquid:mana> * 144, 500, <Thaumcraft:blockCosmeticSolid:4>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:swordBlade:31>, <liquid:mana> * 144, 500, <Thaumcraft:blockCosmeticSolid:4>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:wideGuard:31>, <liquid:mana> * 72, 500, <Thaumcraft:blockCosmeticSolid:4>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:handGuard:31>, <liquid:mana> * 72, 500, <Thaumcraft:blockCosmeticSolid:4>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:crossbar:31>, <liquid:mana> * 72, 500, <Thaumcraft:blockCosmeticSolid:4>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:binding:31>, <liquid:mana> * 72, 500, <Thaumcraft:blockCosmeticSolid:4>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:frypanHead:31>, <liquid:mana> * 144, 500, <Thaumcraft:blockCosmeticSolid:4>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:signHead:31>, <liquid:mana> * 144, 500, <Thaumcraft:blockCosmeticSolid:4>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:knifeBlade:31>, <liquid:mana> * 72, 500, <Thaumcraft:blockCosmeticSolid:4>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:chiselHead:31>, <liquid:mana> * 72, 500, <Thaumcraft:blockCosmeticSolid:4>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:toughRod:31>, <liquid:mana> * 432, 500, <Thaumcraft:blockCosmeticSolid:4>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:toughBinding:31>, <liquid:mana> * 432, 500, <Thaumcraft:blockCosmeticSolid:4>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:heavyPlate:31>, <liquid:mana> * 1152, 500, <Thaumcraft:blockCosmeticSolid:4>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:broadAxeHead:31>, <liquid:mana> * 1152, 500, <Thaumcraft:blockCosmeticSolid:4>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:scytheBlade:31>, <liquid:mana> * 1152, 500, <Thaumcraft:blockCosmeticSolid:4>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:excavatorHead:31>, <liquid:mana> * 1152, 500, <Thaumcraft:blockCosmeticSolid:4>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:largeSwordBlade:31>, <liquid:mana> * 1152, 500, <Thaumcraft:blockCosmeticSolid:4>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:hammerHead:31>, <liquid:mana> * 1152, 500, <Thaumcraft:blockCosmeticSolid:4>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:arrowhead:31>, <liquid:mana> * 144, 500, <Thaumcraft:blockCosmeticSolid:4>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:ShurikenPart:31>, <liquid:mana> * 72, 500, <Thaumcraft:blockCosmeticSolid:4>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:CrossbowLimbPart:31>, <liquid:mana> * 576, 500, <Thaumcraft:blockCosmeticSolid:4>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:CrossbowBodyPart:31>, <liquid:mana> * 720, 500, <Thaumcraft:blockCosmeticSolid:4>);
mods.tconstruct.Smeltery.addMelting(<TConstruct:BowLimbPart:31>, <liquid:mana> * 216, 500, <Thaumcraft:blockCosmeticSolid:4>);

mods.tconstruct.Smeltery.addMelting(<ThermalFoundation:material:516>, <liquid:mana> * 576, 500, <Thaumcraft:blockCosmeticSolid:4>);
mods.tconstruct.Smeltery.addMelting(<Thaumcraft:ItemBootsThaumium>, <liquid:mana> * 576, 500, <Thaumcraft:blockCosmeticSolid:4>);
mods.tconstruct.Smeltery.addMelting(<Thaumcraft:ItemLeggingsThaumium>, <liquid:mana> * 1008, 500, <Thaumcraft:blockCosmeticSolid:4>);
mods.tconstruct.Smeltery.addMelting(<Thaumcraft:ItemChestplateThaumium>, <liquid:mana> * 1152, 500, <Thaumcraft:blockCosmeticSolid:4>);
mods.tconstruct.Smeltery.addMelting(<Thaumcraft:ItemHelmetThaumium>, <liquid:mana> * 720, 500, <Thaumcraft:blockCosmeticSolid:4>);

#Casting
mods.tconstruct.Casting.addTableRecipe(<Thaumcraft:ItemResource:16>, <liquid:voidmetal.molten> * 144, <TConstruct:metalPattern:0>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:toolrod:172>, <liquid:voidmetal.molten> * 72, <TConstruct:metalPattern:1>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:pickaxeHead:172>, <liquid:voidmetal.molten> * 144, <TConstruct:metalPattern:2>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:shovelHead:172>, <liquid:voidmetal.molten> * 144, <TConstruct:metalPattern:3>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:axeHead:172>, <liquid:voidmetal.molten> * 144, <TConstruct:metalPattern:4>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:swordBlade:172>, <liquid:voidmetal.molten> * 144, <TConstruct:metalPattern:5>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:largeGuard:172>, <liquid:voidmetal.molten> * 72, <TConstruct:metalPattern:6>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:mediumGuard:172>, <liquid:voidmetal.molten> * 72, <TConstruct:metalPattern:7>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:crossbar:172>, <liquid:voidmetal.molten> * 72, <TConstruct:metalPattern:8>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:binding:172>, <liquid:voidmetal.molten> * 72, <TConstruct:metalPattern:9>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:frypanHead:172>, <liquid:voidmetal.molten> * 144, <TConstruct:metalPattern:10>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:battelSign:172>, <liquid:voidmetal.molten> * 144, <TConstruct:metalPattern:11>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:knifeBlade:172>, <liquid:voidmetal.molten> * 72, <TConstruct:metalPattern:12>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:chiselHead:172>, <liquid:voidmetal.molten> * 72, <TConstruct:metalPattern:13>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:toughrod:172>, <liquid:voidmetal.molten> * 432, <TConstruct:metalPattern:14>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:toughbind:172>, <liquid:voidmetal.molten> * 432, <TConstruct:metalPattern:15>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:largeplate:172>, <liquid:voidmetal.molten> * 1152, <TConstruct:metalPattern:16>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:lumberaxeHead:172>, <liquid:voidmetal.molten> * 1152, <TConstruct:metalPattern:17>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:scytheHead:172>, <liquid:voidmetal.molten> * 1152, <TConstruct:metalPattern:18>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:excavatorHead:172>, <liquid:voidmetal.molten> * 1152, <TConstruct:metalPattern:19>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:largeSwordBlade:172>, <liquid:voidmetal.molten> * 1152, <TConstruct:metalPattern:20>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:hammerHead:172>, <liquid:voidmetal.molten> * 1152, <TConstruct:metalPattern:21>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:fullGuard:172>, <liquid:voidmetal.molten> * 432, <TConstruct:metalPattern:22>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:arrowhead:172>, <liquid:voidmetal.molten> * 144, <TConstruct:metalPattern:25>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:shuriken:172>, <liquid:voidmetal.molten> * 72, <TConstruct:Cast:0>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:CrossbowLimb:172>, <liquid:voidmetal.molten> * 576, <TConstruct:Cast:1>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:CrossbowBody:172>, <liquid:voidmetal.molten> * 720, <TConstruct:Cast:2>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<ExtraTiC:BowLimb:172>, <liquid:voidmetal.molten> * 216, <TConstruct:Cast:3>, false, 100);

mods.tconstruct.Casting.addBasinRecipe(<Thaumcraft:blockCosmeticSolid:4>, <liquid:mana> * 1296, null, false, 300);
mods.tconstruct.Casting.addTableRecipe(<Thaumcraft:ItemResource:2>, <liquid:mana> * 144, <TConstruct:metalPattern:0>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:toolRod:31>, <liquid:mana> * 72, <TConstruct:metalPattern:1>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:pickaxeHead:31>, <liquid:mana> * 144, <TConstruct:metalPattern:2>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:shovelHead:31>, <liquid:mana> * 144, <TConstruct:metalPattern:3>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:hatchetHead:31>, <liquid:mana> * 144, <TConstruct:metalPattern:4>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:swordBlade:31>, <liquid:mana> * 144, <TConstruct:metalPattern:5>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:wideGuard:31>, <liquid:mana> * 72, <TConstruct:metalPattern:6>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:handGuard:31>, <liquid:mana> * 72, <TConstruct:metalPattern:7>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:crossbar:31>, <liquid:mana> * 72, <TConstruct:metalPattern:8>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:binding:31>, <liquid:mana> * 72, <TConstruct:metalPattern:9>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:frypanHead:31>, <liquid:mana> * 144, <TConstruct:metalPattern:10>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:signHead:31>, <liquid:mana> * 144, <TConstruct:metalPattern:11>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:knifeBlade:31>, <liquid:mana> * 72, <TConstruct:metalPattern:12>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:chiselHead:31>, <liquid:mana> * 72, <TConstruct:metalPattern:13>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:toughRod:31>, <liquid:mana> * 432, <TConstruct:metalPattern:14>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:toughBinding:31>, <liquid:mana> * 432, <TConstruct:metalPattern:15>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:heavyPlate:31>, <liquid:mana> * 1152, <TConstruct:metalPattern:16>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:broadAxeHead:31>, <liquid:mana> * 1152, <TConstruct:metalPattern:17>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:scytheBlade:31>, <liquid:mana> * 1152, <TConstruct:metalPattern:18>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:excavatorHead:31>, <liquid:mana> * 1152, <TConstruct:metalPattern:19>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:largeSwordBlade:31>, <liquid:mana> * 1152, <TConstruct:metalPattern:20>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:hammerHead:31>, <liquid:mana> * 1152, <TConstruct:metalPattern:21>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:arrowhead:31>, <liquid:mana> * 144, <TConstruct:metalPattern:25>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:ShurikenPart:31>, <liquid:mana> * 72, <TConstruct:Cast:0>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:CrossbowLimbPart:31>, <liquid:mana> * 576, <TConstruct:Cast:1>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:CrossbowBodyPart:31>, <liquid:mana> * 720, <TConstruct:Cast:2>, false, 100);
mods.tconstruct.Casting.addTableRecipe(<TConstruct:BowLimbPart:31>, <liquid:mana> * 216, <TConstruct:Cast:3>, false, 100);

#Alloying
mods.tconstruct.Smeltery.addAlloy(<liquid:mana> * 72, [<liquid:obsidian.molten> * 72, <liquid:iron.molten> * 36, <liquid:pyrotheum> * 50, <liquid:mithril.molten> * 72]);
mods.tconstruct.Smeltery.addAlloy(<liquid:voidmetal.molten> * 72, [<liquid:blood> * 144, <liquid:ender> * 72, <liquid:gold.molten> * 36, <liquid:pokefennium.molten> * 108, <liquid:mana> * 144]);
